#
# MCIE088:accessifywiki Nick$ appcfg.py --email=n.d.fr~r@gmail.com update ./
# https://gist.github.com/cagatay/1296386#file-app-yaml
#
application: accessifywiki--1
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /schema/accessify-base-json-schema\.json
  static_files: schema/accessify-base-json-schema.json
  upload: schema/accessify-base-json-schema\.json

- url: /accessifyhtml5.js
  static_dir: lib/accessifyhtml5

- url: /browser
  static_dir: browser

#- url: /(.*\.js)
#- url: /(data/.*\.ya?ml)
#  mime_type: "text/plain; charset=utf-8"
- url: /data
  static_dir: data
  mime_type: text/plain

#- url: /wiki/.*
#  script: wiki/moin.application

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
