#
# MCIE088:accessifywiki Nick$ appcfg.py --email=n.d.fr~r@gmail.com update ./
# https://gist.github.com/cagatay/1296386#file-app-yaml
#
application: accessifywiki--1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "15m"  # Default "10m"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /schema/accessify-base-json-schema\.json
  static_files: schema/accessify-base-json-schema.json
  upload: schema/accessify-base-json-schema\.json

- url: /(.+\.(markdown|md|txt|ya?ml))
  static_files: \1
  upload: (.+\.(markdown|md|txt|ya?ml))
  mime_type: text/plain; charset=utf-8

- url: /accessifyhtml5.js
  static_dir: lib/accessifyhtml5

- url: /(browser/js/.+)-v-(\w+)\.(min\.js|js)
  static_files: \1.\3
  upload: (browser/js/.+)-v-(\w+)\.(min\.js|js)
  expiration: 30m

- url: /(browser/pix/)(\w/\w{2}/)([\w\-]+\.png)
  static_files: \1\3
  upload: (browser/pix/)(\w/\w{2}/)([\w\-]+\.png)
  expiration: 30m

- url: /browser
  static_dir: browser

- url: /data
  static_dir: data

- url: /(.+example.+\.html)
  static_files: \1
  upload: (.+example.+\.html)
  http_headers:
      X-Foo: bar

- url: /site
  static_dir: site

- url: /translate
  static_dir: translate
  mime_type: text/plain; charset=utf-8

#- url: /wiki/.*
#  script: wiki/moin.application

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"


# Ignore files.
skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- Makefile
- .*\.diff
#- .*\.pot


#End.
